var express = require("express");
var online = process.env.online;
var app = express();
app.use(express.static(__dirname));
if (online == "true") {
  app.get("", function (request, response) {
    response.sendFile(__dirname + "/homepage.html");
  });
} else if (online == "update") {
  app.get("", function (request, response) {
    response.sendFile(__dirname + "/error/updating.html");
  });
} else {
  app.get("", function (request, response) {
    response.sendFile(__dirname + "/error/maintenance.html");
  });
}
app.use((req, res) => {
  res.status(404).sendFile(__dirname + "/error/404.html");
});
app.use((req, res) => {
  res.status(403).sendFile(__dirname + "/error/403.html");
});
app.listen(8080);

// FunBot Source Code
const http = require("http");
app.get("/", (request, response) => {
  console.log(Date.now() + "Ping Received");
  response.sendStatus(200);
});
app.listen(process.env.PORT);
const Discord = require("discord.js");
const client = new Discord.Client({ intents: ["GUILDS", "GUILD_MESSAGES"] });
if (online == "true") {
  client.on("ready", async () => {
    console.log(`bot is online!`);
    client.user.setActivity("no. | ?help | ?about | ?invite", {
      type: "WATCHING",
    });
  });
} else {
  client.on("ready", async () => {
    console.log(`bot is inactive.`);
    client.user.setActivity("a maintenance. | ?help | ?about | ?invite", {
      type: "COMPETING",
    });
    client.user.setStatus("idle");
  });
}

client.login(process.env.token);

client.on("messageCreate", async (message) => {
  let prefix = "?";
  let msg = message.content.toLowerCase();
  let args = message.content.slice(prefix.length).trim().split(" ");
  let cmd = args.shift().toLowerCase();

  if (!message.content.startsWith(prefix)) return;

  try {
    let cmdFile = require(`~/commands/${cmd}.js`);
    cmdFile.run(Discord, client, message, args);
  } catch (err) {
    console.log(err);
  }
});
console.log("Active.");

var Base64 = require("Base64");
var decode = Base64.atob(
  "eyJtb25leSI6IjEuNzUwNDU2MzA2OTA5MWUrODMiLCJ0aWNrU3BlZWRDb3N0IjoiMWUrODMiLCJ0aWNrc3BlZWQiOiIwLjA4OTM3MTgwNTQ3OTQ1NDIyIiwiZmlyc3RDb3N0IjoiMWUrODIiLCJzZWNvbmRDb3N0IjoiMWUrODIiLCJ0aGlyZENvc3QiOiIxZSs4NCIsImZvdXJ0aENvc3QiOiIxZSs4NCIsImZpZnRoQ29zdCI6IjFlKzg5Iiwic2l4dGhDb3N0IjoiMWUrODMiLCJzZXZlbnRoQ29zdCI6IjFlKzkwIiwiZWlnaHRDb3N0IjoiMWUrODQiLCJmaXJzdEFtb3VudCI6IjkuMjAwNDkyNzEwMjE5OTZlKzY3Iiwic2Vjb25kQW1vdW50IjoiNi45MzM2MTk2MzQ1MjA5NmUrNTUiLCJ0aGlyZEFtb3VudCI6IjEuMjAwOTE0ODEyMTMxODFlKzQ1IiwiZm91cnRoQW1vdW50IjoiMS42ODIwMzM3NTE5MzY4NGUrMzUiLCJmaXJzdEJvdWdodCI6MjcwLCJzZWNvbmRCb3VnaHQiOjIwMCwidGhpcmRCb3VnaHQiOjE2MCwiZm91cnRoQm91Z2h0IjoxMzAsImZpZnRoQW1vdW50IjoiMS43MzMxNzc3MjQyOTA5NWUrMjYiLCJzaXh0aEFtb3VudCI6IjExMzMyNTEyNDk4Njk0NDAwMDAiLCJzZXZlbnRoQW1vdW50IjoiMTk2NTY3MDIwNzIuNTQ1MDAyIiwiZWlnaHRBbW91bnQiOiI0MCIsImZpZnRoQm91Z2h0IjoxMDAsInNpeHRoQm91Z2h0Ijo3MCwic2V2ZW50aEJvdWdodCI6NjAsImVpZ2h0Qm91Z2h0Ijo0MCwic2FjcmlmaWNlZCI6IjIuMjM2NDUyOTU5NDU2MzJlKzQ4IiwiYWNoaWV2ZW1lbnRzIjpbInIxMSIsInIxMiIsInIxMyIsInIxNCIsInIyMiIsInMzMSIsInIxNSIsInIzNSIsInIxNiIsInIxNyIsInI3NiIsInIxOCIsInI0MiIsInMxOCIsInIyNCIsInI0NiJdLCJjaGFsbGVuZ2VzIjpbXSwiY3VycmVudENoYWxsZW5nZSI6IiIsImluZmluaXR5VXBncmFkZXMiOltdLCJpbmZpbml0eVBvaW50cyI6IjAiLCJpbmZpbml0aWVkIjowLCJpbmZpbml0aWVkQmFuayI6MCwidG90YWxUaW1lUGxheWVkIjoyMzY4Njc4My4wNzk4MTgwMiwiYmVzdEluZmluaXR5VGltZSI6OTk5OTk5OTk5OSwidGhpc0luZmluaXR5VGltZSI6MjM2ODY3ODMuMDc5ODE4MDIsImZpcnN0UG93IjoiMzQzNTk3MzgzNjguMDAwMDEiLCJzZWNvbmRQb3ciOiIxMzQyMTc3MjguMDAwMDAwMDMiLCJ0aGlyZFBvdyI6IjQxOTQzMDQuMDAwMDAwMDAxIiwiZm91cnRoUG93IjoiMjYyMTQ0IiwiZmlmdGhQb3ciOiIxNjM4NCIsInNpeHRoUG93IjoiMTAyNCIsInNldmVudGhQb3ciOiIyNTYiLCJlaWdodFBvdyI6IjczNy4yOCIsInJlc2V0cyI6OCwiZ2FsYXhpZXMiOjAsInRpY2tEZWNyZWFzZSI6MC45LCJ0b3RhbG1vbmV5IjoiMS4xNjQxNjQyNTIxNDU2OGUrMTI2IiwiaW50ZXJ2YWwiOm51bGwsImxhc3RVcGRhdGUiOjE2NDE4Mzg2MjM0MTMsImFjaFBvdyI6IjEuNSIsIm5ld3NBcnJheSI6WyJhOTkiLCJhNTQiLCJhNzMiLCJhMTMxIiwiYTExNiIsImE5MSIsImExMDIiLCJhODAiLCJhOTQiLCJhNTUiLCJhMzQiLCJhOTgiLCJhMzMiLCJhOCIsImE2IiwiYTEyNiIsImE4MiIsImExMjciLCJhMTEzIiwiYTEyMyIsImExMTAiLCJhOTciLCJhNzYiLCJhNzQiLCJhNDAiLCJhMTI0IiwiYTEzMyIsInBhdDEiLCJhMTE4IiwiYTgxIiwiYTM2IiwiYTY0IiwiYTEyMSIsImE2OCIsImEyOCIsImEyNSIsImExMjAiLCJhODUiLCJhMTAwIiwiYTEwMSIsImExNSIsImExMDMiLCJuMyIsImE4MyIsImE4NCIsImE5IiwiYTQzIiwiYTcxIiwiYTUxIiwiYTE4IiwiYTcyIiwiYTEzNiIsImEyMSIsImE0NSIsImE1MyIsImEyNiIsImExMzAiLCJhMiIsImExMyIsImExMzgiLCJhNTYiLCJhNjMiLCJhMTYiLCJhNDQiLCJhMTkiLCJhNjAiLCJhMTI1IiwiYTEwOCIsImExMTQiLCJhMTIiLCJhMTM1IiwiYTg2IiwiYTEzNyIsImEzOCIsImE3OSIsImEzMCIsImExMjgiLCJhNzUiLCJhMyIsImEzNyIsImExMCIsImExMDUiLCJhODkiLCJhNjYiLCJhMTI5IiwiYTc4IiwiYTMyIiwiYTQ4IiwiYTQiLCJhNjkiLCJhMzEiLCJhMzkiLCJhODgiLCJhMTE1IiwiYTEwNiIsImE0NyIsImExMzIiLCJhNzAiLCJhMTE5IiwiYTEzNCIsIm4xIiwiYTk2IiwiYjMiLCJhNTgiLCJuNyIsImE0OSIsImEyOSIsImExIiwiYTEwNCIsIm44IiwiYTkwIiwiYTQ2IiwiYTEwOSIsImExNCIsImExMDciLCJhMjIiLCJiNSIsImE3IiwiYTQxIiwibjUiLCJhNTkiLCJhNjUiLCJhOTMiLCJhNzciLCJhNTIiLCJhNSIsImEyNCIsImE0MiIsImE4NyIsImE5MiIsImEyMCIsImE2NyIsImEyMyIsImExNyIsImExMTciLCJhMTEiLCJhMTIyIiwiYTk1IiwiYTM1IiwiYTYxIiwibjIiLCJhMTEyIiwiYTU3IiwiYTExMSIsImIxMyIsImEyNyIsImE1MCIsImI2IiwiYjEwIiwiYjI0IiwiYjE3IiwiYjIyIiwiYTYyIiwiYjE0IiwiYjciLCJiMTIiLCJjNiIsIm42Il0sImF1dG9idXllcnMiOlsxLDIsMyw0LDUsNiw3LDgsOSwxMCwxMSwxMl0sImNvc3RNdWx0aXBsaWVycyI6WyIxMDAwIiwiMTAwMDAiLCIxMDAwMDAiLCIxMDAwMDAwIiwiMTAwMDAwMDAwIiwiMTAwMDAwMDAwMDAiLCIxMDAwMDAwMDAwMDAwIiwiMTAwMDAwMDAwMDAwMDAwMCJdLCJ0aWNrc3BlZWRNdWx0aXBsaWVyIjoiMTAiLCJjaGFsbDJQb3ciOjEsImNoYWxsM1BvdyI6IjAuMDEiLCJtYXR0ZXIiOiIwIiwiY2hhbGwxMVBvdyI6IjEiLCJwYXJ0SW5maW5pdHlQb2ludCI6MCwicGFydEluZmluaXRpZWQiOjAsImJyZWFrIjpmYWxzZSwiY2hhbGxlbmdlVGltZXMiOlsyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMCwyNjc4NDAwMF0sImluZmNoYWxsZW5nZVRpbWVzIjpbMjY3ODQwMDAsMjY3ODQwMDAsMjY3ODQwMDAsMjY3ODQwMDAsMjY3ODQwMDAsMjY3ODQwMDAsMjY3ODQwMDAsMjY3ODQwMDBdLCJsYXN0VGVuUnVucyI6W1syNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdLFsyNjc4NDAwMCwiMSJdXSwibGFzdFRlbkV0ZXJuaXRpZXMiOltbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXSxbMjY3ODQwMDAsIjEiXV0sImluZk11bHQiOiIxIiwiaW5mTXVsdENvc3QiOiIxMCIsInRpY2tTcGVlZE11bHREZWNyZWFzZSI6MTAsInRpY2tTcGVlZE11bHREZWNyZWFzZUNvc3QiOjMwMDAwMDAsImRpbWVuc2lvbk11bHREZWNyZWFzZSI6MTAsImRpbWVuc2lvbk11bHREZWNyZWFzZUNvc3QiOjEwMDAwMDAwMCwidmVyc2lvbiI6MTIuMywib3ZlclhHYWxheGllcyI6MTAsImluZkRpbWVuc2lvbnNVbmxvY2tlZCI6W2ZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlXSwiaW5maW5pdHlQb3dlciI6IjEiLCJzcHJlYWRpbmdDYW5jZXIiOjAsInBvc3RDaGFsbFVubG9ja2VkIjowLCJwb3N0QzRUaWVyIjo1LCJwb3N0QzNSZXdhcmQiOiIxIiwiaW5maW5pdHlEaW1lbnNpb24xIjp7ImNvc3QiOiIxMDAwMDAwMDAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5maW5pdHlEaW1lbnNpb24yIjp7ImNvc3QiOiIxMDAwMDAwMDAwIiwiYW1vdW50IjoiMCIsImJvdWdodCI6MCwicG93ZXIiOiIxIiwiYmFzZUFtb3VudCI6MH0sImluZmluaXR5RGltZW5zaW9uMyI6eyJjb3N0IjoiMTAwMDAwMDAwMDAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5maW5pdHlEaW1lbnNpb240Ijp7ImNvc3QiOiIxMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5maW5pdHlEaW1lbnNpb241Ijp7ImNvc3QiOiIxZSsxNDAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5maW5pdHlEaW1lbnNpb242Ijp7ImNvc3QiOiIxZSsyMDAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5maW5pdHlEaW1lbnNpb243Ijp7ImNvc3QiOiIxZSsyNTAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5maW5pdHlEaW1lbnNpb244Ijp7ImNvc3QiOiIxZSsyODAiLCJhbW91bnQiOiIwIiwiYm91Z2h0IjowLCJwb3dlciI6IjEiLCJiYXNlQW1vdW50IjowfSwiaW5mRGltQnV5ZXJzIjpbZmFsc2UsZmFsc2UsZmFsc2UsZmFsc2UsZmFsc2UsZmFsc2UsZmFsc2UsZmFsc2VdLCJ0aW1lU2hhcmRzIjoiMCIsInRpY2tUaHJlc2hvbGQiOiIxIiwidGltZURpbWVuc2lvbjEiOnsiY29zdCI6IjEiLCJhbW91bnQiOiIwIiwicG93ZXIiOiIxIiwiYm91Z2h0IjowfSwidGltZURpbWVuc2lvbjIiOnsiY29zdCI6IjUiLCJhbW91bnQiOiIwIiwicG93ZXIiOiIxIiwiYm91Z2h0IjowfSwidGltZURpbWVuc2lvbjMiOnsiY29zdCI6IjEwMCIsImFtb3VudCI6IjAiLCJwb3dlciI6IjEiLCJib3VnaHQiOjB9LCJ0aW1lRGltZW5zaW9uNCI6eyJjb3N0IjoiMTAwMCIsImFtb3VudCI6IjAiLCJwb3dlciI6IjEiLCJib3VnaHQiOjB9LCJ0aW1lRGltZW5zaW9uNSI6eyJjb3N0IjoiMWUrMjM1MCIsImFtb3VudCI6IjAiLCJwb3dlciI6IjEiLCJib3VnaHQiOjB9LCJ0aW1lRGltZW5zaW9uNiI6eyJjb3N0IjoiMWUrMjY1MCIsImFtb3VudCI6IjAiLCJwb3dlciI6IjEiLCJib3VnaHQiOjB9LCJ0aW1lRGltZW5zaW9uNyI6eyJjb3N0IjoiMWUrMzAwMCIsImFtb3VudCI6IjAiLCJwb3dlciI6IjEiLCJib3VnaHQiOjB9LCJ0aW1lRGltZW5zaW9uOCI6eyJjb3N0IjoiMWUrMzM1MCIsImFtb3VudCI6IjAiLCJwb3dlciI6IjEiLCJib3VnaHQiOjB9LCJldGVybml0eVBvaW50cyI6IjAiLCJldGVybml0aWVzIjowLCJ0aGlzRXRlcm5pdHkiOjIzNjg2NzgzLjA3OTgxODAyLCJiZXN0RXRlcm5pdHkiOjk5OTk5OTk5OTksImV0ZXJuaXR5VXBncmFkZXMiOltdLCJlcG11bHQiOiIxIiwiZXBtdWx0Q29zdCI6IjUwMCIsInRvdGFsVGlja0dhaW5lZCI6MCwib2ZmbGluZVByb2QiOjAsIm9mZmxpbmVQcm9kQ29zdCI6MTAwMDAwMDAsImNoYWxsZW5nZVRhcmdldCI6MCwiYXV0b1NhY3JpZmljZSI6MSwicmVwbGljYW50aSI6eyJhbW91bnQiOiIwIiwidW5sIjpmYWxzZSwiY2hhbmNlIjowLjAxLCJjaGFuY2VDb3N0IjoiMWUrMTUwIiwiaW50ZXJ2YWwiOjEwMDAsImludGVydmFsQ29zdCI6IjFlKzE0MCIsImdhbCI6MCwiZ2FsYXhpZXMiOjAsImdhbENvc3QiOiIxZSsxNzAiLCJhdXRvIjpbZmFsc2UsZmFsc2UsZmFsc2VdfSwidGltZXN0dWR5Ijp7InRoZW9yZW0iOjAsImFtY29zdCI6IjFlKzIwMDAwIiwiaXBjb3N0IjoiMSIsImVwY29zdCI6IjEiLCJzdHVkaWVzIjpbXX0sImV0ZXJuaXR5Q2hhbGxzIjp7fSwiZXRlcm5pdHlDaGFsbEdvYWwiOiIxLjc5NzY5MzEzNDg2MjMxNTdlKzMwOCIsImN1cnJlbnRFdGVybml0eUNoYWxsIjoiIiwiZXRlcm5pdHlDaGFsbFVubG9ja2VkIjowLCJldGVyY3JlcSI6MCwiYXV0b0lQIjoiMCIsImF1dG9UaW1lIjoxZSszMDAsImluZk11bHRCdXllciI6ZmFsc2UsImF1dG9DcnVuY2hNb2RlIjoiYW1vdW50IiwicmVzcGVjIjpmYWxzZSwiZXRlcm5pdHlCdXllciI6eyJsaW1pdCI6IjAiLCJpc09uIjp0cnVlfSwiZXRlcmM4aWRzIjo1MCwiZXRlcmM4cmVwbCI6NDAsImRpbWxpZmUiOmZhbHNlLCJkZWFkIjpmYWxzZSwiZGlsYXRpb24iOnsic3R1ZGllcyI6W10sImFjdGl2ZSI6ZmFsc2UsInRhY2h5b25QYXJ0aWNsZXMiOiIwIiwiZGlsYXRlZFRpbWUiOiIwIiwidG90YWxUYWNoeW9uUGFydGljbGVzIjoiMCIsIm5leHRUaHJlc2hvbGQiOiIxMDAwIiwiZnJlZUdhbGF4aWVzIjowLCJ1cGdyYWRlcyI6W10sInJlYnV5YWJsZXMiOnsiMSI6MCwiMiI6MCwiMyI6MH19LCJ3aHkiOjI5MCwib3B0aW9ucyI6eyJuZXdzSGlkZGVuIjpmYWxzZSwibm90YXRpb24iOiJTdGFuZGFyZCIsInNjaWVudGlmaWMiOmZhbHNlLCJjaGFsbENvbmYiOmZhbHNlLCJzYWNyaWZpY2VDb25maXJtYXRpb24iOnRydWUsInJldHJ5Q2hhbGxlbmdlIjpmYWxzZSwiYnVsa09uIjp0cnVlLCJjbG91ZCI6dHJ1ZSwiaG90a2V5cyI6dHJ1ZSwic2VjcmV0VGhlbWVLZXkiOjAsImV0ZXJuaXR5Y29uZmlybSI6dHJ1ZSwiY29tbWFzIjp0cnVlLCJ1cGRhdGVSYXRlIjozMywiY2hhcnQiOnsidXBkYXRlUmF0ZSI6MTAwMCwiZHVyYXRpb24iOjEwLCJ3YXJuaW5nIjowLCJvbiI6ZmFsc2UsImRpcHMiOnRydWV9LCJhbmltYXRpb25zIjp7ImZsb2F0aW5nVGV4dCI6ZmFsc2UsImJpZ0NydW5jaCI6dHJ1ZSwiZXRlcm5pdHkiOnRydWUsInRhY2h5b25QYXJ0aWNsZXMiOnRydWV9LCJ0aGVtZXMiOiJOb3JtYWwifX0="
);
console.warn(decode);